#!/usr/bin/env bash
# Shared helpers for offline-readonly-backup scripts.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
fi

export CHAD_OFFLINE_READONLY_BACKUP_ROOT="${CHAD_OFFLINE_READONLY_BACKUP_ROOT:-$HOME/04_chad_offline_readonly_backup}"
export OFFLINE_READONLY_BACKUP_POSTGRES_PORT="${OFFLINE_READONLY_BACKUP_POSTGRES_PORT:-55432}"
export OFFLINE_READONLY_BACKUP_ADMIN_USER="${OFFLINE_READONLY_BACKUP_ADMIN_USER:-chad_offline_readonly_backup_admin}"
export OFFLINE_READONLY_BACKUP_ADMIN_PASSWORD="${OFFLINE_READONLY_BACKUP_ADMIN_PASSWORD:-}"
export OFFLINE_READONLY_BACKUP_READER_PASSWORD="${OFFLINE_READONLY_BACKUP_READER_PASSWORD:-}"
export OFFLINE_READONLY_BACKUP_SOURCE_HOST="${OFFLINE_READONLY_BACKUP_SOURCE_HOST:-100.117.139.83}"
export OFFLINE_READONLY_BACKUP_SOURCE_PORT="${OFFLINE_READONLY_BACKUP_SOURCE_PORT:-12042}"
export OFFLINE_READONLY_BACKUP_SOURCE_DB="${OFFLINE_READONLY_BACKUP_SOURCE_DB:-chad}"
export OFFLINE_READONLY_BACKUP_SOURCE_USER="${OFFLINE_READONLY_BACKUP_SOURCE_USER:-chad}"

CONTAINER_NAME="chad-postgres-offline-readonly-backup"
DB_NAME="chad_offline_readonly_backup"
READER_ROLE="chad_offline_readonly_backup_reader"

ensure_dirs() {
  mkdir -p \
    "$CHAD_OFFLINE_READONLY_BACKUP_ROOT/postgres-data" \
    "$CHAD_OFFLINE_READONLY_BACKUP_ROOT/backups" \
    "$CHAD_OFFLINE_READONLY_BACKUP_ROOT/restore-logs" \
    "$CHAD_OFFLINE_READONLY_BACKUP_ROOT/metadata"
}

admin_uri() {
  echo "postgres://${OFFLINE_READONLY_BACKUP_ADMIN_USER}:${OFFLINE_READONLY_BACKUP_ADMIN_PASSWORD}@127.0.0.1:${OFFLINE_READONLY_BACKUP_POSTGRES_PORT}/${DB_NAME}"
}

reader_uri() {
  echo "postgres://${READER_ROLE}:${OFFLINE_READONLY_BACKUP_READER_PASSWORD}@127.0.0.1:${OFFLINE_READONLY_BACKUP_POSTGRES_PORT}/${DB_NAME}"
}

apply_readonly_role() {
  local admin_uri="$1"
  local reader_pass="${OFFLINE_READONLY_BACKUP_READER_PASSWORD:?OFFLINE_READONLY_BACKUP_READER_PASSWORD is required}"
  psql "$admin_uri" -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${READER_ROLE}') THEN
    CREATE ROLE ${READER_ROLE} LOGIN PASSWORD '${reader_pass}';
  ELSE
    ALTER ROLE ${READER_ROLE} WITH PASSWORD '${reader_pass}';
  END IF;
END
\$\$;
REVOKE ALL ON DATABASE ${DB_NAME} FROM PUBLIC;
GRANT CONNECT ON DATABASE ${DB_NAME} TO ${READER_ROLE};
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO ${READER_ROLE};
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${READER_ROLE};
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${READER_ROLE};
ALTER ROLE ${READER_ROLE} SET default_transaction_read_only = on;
SQL
}
